version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 2s
      timeout: 2s
      retries: 3


  app:
      depends_on:
        postgres:
          condition: service_healthy
      build: .
      container_name: cart_api
      restart: unless-stopped
      ports:
        - ${API_PORT}:${API_PORT}