version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 2s
      timeout: 2s
      retries: 3


# add environment variables to compose

  app:
    build: .
    container_name: cart_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy